name: Check

on:
  pull_request:

  push:
    branches:
      - 2.9.x # Check branch after merge

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    uses: playframework/.github/.github/workflows/cmd.yml@v3
    with:
      java: 21, 17, 11
      scala: 2.13.x, 3.x
      cmd: |
        cd code;
        sbt ++$MATRIX_SCALA publishLocal;
        sbt ++$MATRIX_SCALA -DplayTestVersion=2.9.5 test;
        cd ../test-app;
        sbt ++$MATRIX_SCALA -DplayTestVersion=2.9.5 test;
        cd ../test-app-filters;
        sbt ++$MATRIX_SCALA -DplayTestVersion=2.9.5 test;
        cd ../code;

  finish:
    name: Finish
    if: github.event_name == 'pull_request'
    needs: # Should be last
      - "tests"
    uses: playframework/.github/.github/workflows/rtm.yml@v3
